<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getArticleByTag($tag = NULL, $page=1, $maxperpage=10, $titlesearch=null){
        $qb = $this->createQueryBuilder('a');
        $qb->select('a.id', 'a.title', 'a.subtitle','a.image', 'a.content');
        $qb->where('a.visible = 1');
            if($tag != NULL) {
                $qb->andWhere('t.name = :tag');
                $qb->setParameter('tag', $tag);
                $qb->innerJoin('a.tags', 't');
            };
        $qb->orderBy('a.created', 'DESC');
        $qb->setFirstResult(($page-1) * $maxperpage);
        $qb->setMaxResults($maxperpage);
        return $qb->getQuery()->getResult();
    }
}
